"use client";

import { motion } from "framer-motion";
import { TrendingUp, TrendingDown, FlaskConical, Sparkles } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

interface AuditReportProps {
  reportMarkdown: string;
  recommendation: "SCALE" | "KILL" | "TEST_MORE";
  confidenceScore: number;
  winningVariant?: string | null;
}

const recMeta = {
  SCALE: { label: "Scale", variant: "success" as const, icon: TrendingUp },
  KILL: { label: "Kill", variant: "destructive" as const, icon: TrendingDown },
  TEST_MORE: { label: "Test more", variant: "warning" as const, icon: FlaskConical },
};

// Tiny markdown -> JSX renderer (handles ##, -, paragraphs).
function renderMarkdown(md: string) {
  const lines = md.split("\n");
  const blocks: React.ReactNode[] = [];
  let bulletBuf: string[] = [];

  const flushBullets = (key: number) => {
    if (bulletBuf.length === 0) return;
    blocks.push(
      <ul key={`ul-${key}`} className="space-y-1.5 my-3 ml-4 text-sm list-disc marker:text-muted-foreground">
        {bulletBuf.map((b, i) => (
          <li key={i} className="leading-relaxed">{b}</li>
        ))}
      </ul>
    );
    bulletBuf = [];
  };

  lines.forEach((line, i) => {
    if (line.startsWith("## ")) {
      flushBullets(i);
      blocks.push(
        <h3 key={i} className="text-sm font-semibold tracking-tight mt-5 first:mt-0 mb-2">
          {line.slice(3)}
        </h3>
      );
    } else if (line.startsWith("- ")) {
      bulletBuf.push(line.slice(2));
    } else if (line.trim() === "") {
      flushBullets(i);
    } else {
      flushBullets(i);
      blocks.push(
        <p key={i} className="text-sm leading-relaxed text-foreground/90 my-2">
          {line}
        </p>
      );
    }
  });
  flushBullets(lines.length);
  return blocks;
}

export function AuditReport({
  reportMarkdown,
  recommendation,
  confidenceScore,
  winningVariant,
}: AuditReportProps) {
  const meta = recMeta[recommendation];
  const Icon = meta.icon;

  return (
    <motion.div
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4 }}
    >
      <Card className="p-6">
        <div className="flex items-center justify-between mb-5 pb-5 border-b border-border/60">
          <div className="flex items-center gap-3">
            <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-foreground text-background">
              <Sparkles className="h-4 w-4" />
            </div>
            <div>
              <div className="text-sm font-semibold">AI audit report</div>
              <div className="text-[11px] text-muted-foreground">
                Generated by Claude · contractor-vertical benchmarks applied
              </div>
            </div>
          </div>
          <div className="flex items-center gap-2">
            {winningVariant && (
              <Badge variant="outline" className="font-mono text-[10px]">
                Winner: {winningVariant}
              </Badge>
            )}
            <Badge variant={meta.variant} className="gap-1">
              <Icon className="h-3 w-3" />
              {meta.label}
            </Badge>
            <div className="text-[11px] text-muted-foreground tabular-nums">
              {confidenceScore}% confident
            </div>
          </div>
        </div>
        <div className="prose-sm">{renderMarkdown(reportMarkdown)}</div>
      </Card>
    </motion.div>
  );
}
